package block


const (
	DATAHASHKEY = 4
	DATAHASHVAL = 32
	DATAHASH = DATAHASHKEY + DATAHASHVAL

	PREBLOCKHASH = 32
	SIGNTIMESTAMP = 8
	TIMESIGNITURE = 165
	DATASTARTTIME = 8
	DATAENDTIME = 8
	MARKELROOT = 32
	NONCE = 4
	BLOCKHEADSIZE = PREBLOCKHASH + SIGNTIMESTAMP + TIMESIGNITURE + MARKELROOT + NONCE + DATASTARTTIME + DATAENDTIME
	BLOCKSLICEINTERVAL = "BlockSliceInterval"
)
